name: Ubuntu - Install

on: [push]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14
      - name: Build & Install
        run: mvn clean install -DskipTests
