name: Install - Ubuntu

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 13
      - name: Build & Install
        run: mvn clean install -DskipTests
