name: Ubuntu - Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Set up Zalenium
        run: docker-compose -f docker-compose_zalenium.yml up --force-recreate -d
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 13
      - name: Check running containers
        run: docker ps
      - name: Run all tests
        run: mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="false" -DtargetBrowserName="GoogleChrome"
