name: Ubuntu - Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Set up Zalenium
        uses: ajinx/zalenium@v1.1
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 13
      - name: Run all tests
        run: mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="false" -DtargetBrowserName="GoogleChrome"
